//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::organizations::Entity as Organizations;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::users::Entity as Users;
